spring:
  application:
    name: zuul
  rabbitmq:
    host: 176.201.110.129
    port: 5672
    username: admin
    password: admin

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

zuul:
  retryable: true

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 1

#  routes:
#    item-service: "/item-service/**"
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

